#!/usr/bin/env bash

ls -lh

echo "============================================================="

# Comando file para ver los tipos de archivos. El código ASCII, visualiza archivos
#  de texto. .fasta se utiliza para representar secuencias de proteínas y nucleotídicas 
# por ejemplo. 

echo "> Vemos los fipos de ficheros"
file *

echo "============================================================="

# Comandos para mostrar los contenidos de los archivos. 
echo "> Vemos el ejemplo de la secuencia de ADN"
cat sample.fasta
# En vez de ver todo, podemos contar palabras, ver líneas...

echo "> Contamos las líneas de sample.fasta"

wc -l sample.fasta

echo "> Contamos el nº de palabras del ahivo anterior"

wc -w sample.fasta

echo "============================================================="

#### Repite lo mismo pero con otro ejemplo, yo no lo tengo.La idea es ver distintos 
# comandos para ver los archivos largos por partes. voy a ver uno de mis queridos 
# archivos de briófitos.

# Con cat es muy difícil ver el archivo
# cat /mnt/c/Users/jcge9/Desktop/asignaturas_VIU/SO_Linux/videos/video3/Base2briofitos/Crossocalyx_hellerianus_global.txt

# Usaremos otros comandos, los voy a comentar una vez los use, los descomentaré si lo
# queiro volver a ver 
echo "> Comando more se va para abajo con enter"
# more /mnt/c/Users/jcge9/Desktop/asignaturas_VIU/SO_Linux/videos/video3/Base2briofitos/Crossocalyx_hellerianus_global.txt
echo "> Comando less se va para abajo con las flechas del teclado"
# less /mnt/c/Users/jcge9/Desktop/asignaturas_VIU/SO_Linux/videos/video3/Base2briofitos/Crossocalyx_hellerianus_global.txt

echo "============================================================="

# Ver el principio y el final
echo "> head nos muestra las primeras 10 líneas del archivo, con -n elegimos el número de líneas, printeamos las tres primeras línea"
head -n 3 sample.fasta # sólo tengo 1 xd

echo "============================================================="

# Lo siguente que hace es ver una base de datos de una serie de genes que se han sobreexpresados
# yo como no gozo de esa base, voy a tomar los datos de mi amigo brófito: Amphidium mougeotii

## Con esto creamos una base de datos con los individuos de Amphidium mougeotii

# cut -f1 /mnt/c/Users/jcge9/Desktop/asignaturas_VIU/SO_Linux/videos/video3/Base2briofitos/Amphidium_mougeotii.txt > individuos_briofito.txt

echo "> Hemos creado una base de datos sólo con los individuos del briofito anterior y hacemos una copia para compararlos si hiciera falta"
ls -l

## Además lo he copiado en una copia_briofitos.txt, por que me suena que los vamos a comparar

# cp individuos_briofito.txt copia_briofitos.txt

echo "============================================================="

# A los individuos de briofitos los vamos a ordenar alfabéticamente 

echo "> Individuos de briófitos ordenados alfabéticamente"
sort individuos_briofito.txt

echo "Ordenarlos de forma inversa"
sort -R individuos_briofito.txt

# Pasarlo a otro archivo de salida, ya me adelanté con cut con lo cual no lo voy a hacer pero lo
# copio aquí comentado.

# sort individuos_briofito.txt > individuos_briofito_ordenados.txt

echo "============================================================="

# Vamos a juntar los individuos de briófitos con la copia. Para eso unimos línea a línea los archivos. 
# Separándose por tabuladores. Vale, esto no es para ver las diferencias, si no para ponerlos en un
# único archivo.

sort -R copia_briofitos.txt > inverso_copia.txt ; paste individuos_briofito.txt inverso_copia.txt
echo "> Ambos archivos han sido fucionados he invertido la copia, para que sean todos diferentes, me parece complicarlo un poquillo para que no sea tan fácil"

# Podemos especificar el delimitador a fucionar con -d y entre comillas, lo comento abajo

# paste -d ";" individuos_briofito.txt inverso_copia.txt

# Comando diff nos comparará los comandos línea a línea

echo "> Obviamente en este caso no van a haber ninguna diferencia"
diff -y individuos_briofito.txt copia_briofitos.txt 

echo "> En el caso de invertir la copia, todos difieren, ocurre algo raro que no entiendo muy bien xd, parece que se generan espacios entre líneas o algo así, pero bueno, algunos son iguales, con lo cual sirve para enterarse de cómo va la movida"
diff -y individuos_briofito.txt inverso_copia.txt 

echo "============================================================="

# Lo siguiente es separar los campos de interés, partes separados por el tabulador, columnas de 
# toda la vida, vectores para in friki de R como yo. Ah, esto ya lo hice para conseguir los individuos
# del briófito xd.

echo "> Voy a extraer los locusde A.mougeotii y voy a llamar al archivo <locus_A_mougeotii.txt>" 

cut -f4-6 /mnt/c/Users/jcge9/Desktop/asignaturas_VIU/SO_Linux/videos/video3/Base2briofitos/Amphidium_mougeotii.txt > locus_A_mougeotii.txt

ls 

# También puedo separar los carácteres. lo hacemos con cut -c

echo "> Vamos a obtener el primer carácter de los nombres de individuos de A.mougeotii"

cut -c1 individuos_briofito.txt

echo "> NICE, Se acabó por hoy"